###
POST https://mojoapiserver.herokuapp.com/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Sheezeysql12",
    "email": "sqltest12",
    "password": "12345",
    "upline": "11"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "tst",
    "password": "12345"
}

###
POST http://localhost:4000/deposit HTTP/1.1
Content-Type: application/json

{
    "email": "testemail",
    "hash": "8289717312b1f8c720c8c730215ba18e4ec80a97575d7d108c120f8a37b3b57b9e",
    "amount": "16"
}

###
POST http://localhost:4000/payout HTTP/1.1
Content-Type: application/json

{
    "username" : "tst",
    "amount": 36,
    "address": "njeu73yhnej38njddjeu83u8393j"
}
###
POST http://localhost:4000/mine HTTP/1.1
Content-Type: application/json

{
    "email": "investoremoo@gmail.com"
}

###
POST http://localhost:3000/conpayout HTTP/1.1
Content-Type: application/json

{
    "amount": "20", "username": "tst", "id": 40, "status": "confirmed"
}

###
GET http://localhost:3000/

###
GET http://localhost:4000/getpayout/tst

###
GET http://localhost:4000/pendeposit